# Generated by Django 5.1.5 on 2025-02-02 22:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("fbv_people", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="person",
            options={
                "ordering": ["-birthday"],
                "verbose_name": "Person",
                "verbose_name_plural": "People",
            },
        ),
    ]
