# Generated by Django 5.1.5 on 2025-02-03 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ns_books", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="book",
            name="author",
        ),
        migrations.AddField(
            model_name="book",
            name="authors",
            field=models.ManyToManyField(blank=True, to="ns_books.author"),
        ),
    ]
